apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
metadata:
  name: buggy-dropdown-app
  description: "Simple HTML file execution"

pipeline:
  agent:
    docker:
      image: 'nginx:alpine'

  environment:
    APP_NAME: "buggy-dropdown"
    PORT: "8080"

  stages:
    - name: Setup
      steps:
        - checkout:
            scm:
              - git:
                  url: "https://github.com/GokulRajuG/IHGIntegrationtest"
                  branch: main

    - name: Run
      steps:
        - sh: |
            mkdir -p /usr/share/nginx/html
            cp buggy-dropdown.html /usr/share/nginx/html/index.html
            cat > /etc/nginx/conf.d/default.conf << 'EOF'
            server {
                listen ${PORT};
                server_name localhost;
                location / {
                    root /usr/share/nginx/html;
                    index index.html;
                }
            }
            EOF
            nginx -g 'daemon off;'

  options:
    timeout: 10
    timestamps: true

triggers:
  - type: manual
