apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
metadata:
  name: buggy-dropdown-viewer
  description: "View HTML in Chrome"

pipeline:
  agent:
    docker:
      image: 'nginx:alpine'

  environment:
    PORT: "8080"

  stages:
    - name: Setup
      steps:
        - checkout:
            scm:
              - git:
                  url: "https://github.com/GokulRajuG/IHGIntegrationtest"
                  branch: main

    - name: Serve and View
      steps:
        - sh: |
            # Copy HTML file
            mkdir -p /usr/share/nginx/html
            cp buggy-dropdown.html /usr/share/nginx/html/index.html
            
            # Configure nginx
            echo "server { listen ${PORT}; location / { root /usr/share/nginx/html; } }" > /etc/nginx/conf.d/default.conf
            
            # Start nginx and open Chrome
            nginx
            google-chrome http://localhost:${PORT}/index.html

triggers:
  - type: manual
