apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: IHG Test

on:
  push:
    branches:
      - '**'

jobs:
  build:
    steps:
      - name: Dropdown Job
        uses: docker://golang:1.20.3-alpine3.17
    parameters:
        - choice:
          name: "Name Selection"
          choices:
            - "YourName"
          description: "Select your name from the dropdown"
            
    steps 2:
      - label: "Display Name"
        shell: |
        echo "You have selected: ${params['Name Selection']}"