apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: IHG Test

on:
  push:
    branches:
      - '**'

parameters:
  - choice:
      name: "Name Selection"
      choices:
        - "Gokul"
      description: "Select your name from the dropdown"

stages:
  - stage: "Display Name"
    steps:
      - script: |
          echo "You have selected: ${params['Name Selection']}"
